// <auto-generated> from skills/geniusone_platform/scripts/assessment_map/assess_map.py via phase3/rules.py. Edit the Python, regenerate. </auto-generated>
using System;
using System.Linq;
using System.Text.RegularExpressions;

namespace GeniusOneAi.CrisisAssessments.Services
{
    public sealed class Rule
    {
        public int Id; public string Form, Section, Item, Predicate, Domain, Phase, Note, Priority, HardStopTitle, HardStopInstruction; public string[] Needs, GoalCodes;
        public Rule(int id, string form, string section, string item, string pred, string domain, string[] needs, string phase, string[] goals, string note, string priority, string hsTitle, string hsInstr)
        { Id = id; Form = form; Section = section; Item = item; Predicate = pred; Domain = domain; Needs = needs; Phase = phase; GoalCodes = goals; Note = note; Priority = priority; HardStopTitle = hsTitle; HardStopInstruction = hsInstr; }
    }

    public static class AssessmentRules
    {
        public const int AdultTrigger = 4, AdultCutoff = 4, AdultQuestions = 11;
        public const int ChildTrigger = 3, ChildCutoff = 4, ChildQuestions = 20;

        public static readonly Rule[] All = new[]
        {
            new Rule(1, "child", "Location of Service", "school and childcare", "loc=school", "Child, Youth & Family", new[] { "SCHOOL_SUPPORT" }, "E2", new[] { "G-27", "G-68" }, "School-based crisis: school re-entry plan", "Medium", "", ""),
            new Rule(2, "both", "Location of Service", "temporary home / shelter", "loc=temporary_home", "Basic Needs - Shelter & Housing", new[] { "HOUSING" }, "E2", new[] { "G-08", "G-12" }, "", "Medium", "", ""),
            new Rule(3, "both", "Location of Service", "children under 18 live in this home", "childhome", "Child, Youth & Family", new[] { "FAMILY_SUPPORT" }, "E2", new[] { "G-53", "G-100" }, "Screen children in the household", "Medium", "", ""),
            new Rule(4, "both", "Location of Service", "medical center", "loc=medical_center", "Medical & Co-occurring", new[] { "MEDICAL_CARE" }, "E2", new[] { "G-98" }, "Discharge from ED/inpatient: aftercare within 7 days", "Medium", "", ""),
            new Rule(5, "both", "Risk Categories", "family or friend missing/dead", "risk=family_friend_dead|family_dead|friend_dead", "Grief & Loss", new[] { "GRIEF_SUPPORT" }, "E1", new[] { "G-16", "G-17", "G-18", "G-20" }, "Pick by cause of death", "High", "", ""),
            new Rule(6, "both", "Risk Categories", "pet missing/dead", "risk=pet_dead", "Grief & Loss", new[] { "GRIEF_SUPPORT" }, "E2", new[] { "G-16" }, "", "Medium", "", ""),
            new Rule(7, "both", "Risk Categories", "home damaged or destroyed", "risk=home_damaged", "Basic Needs - Shelter & Housing", new[] { "HOUSING", "DISASTER_RECOVERY" }, "E1", new[] { "G-10", "G-11", "G-87" }, "", "High", "", ""),
            new Rule(8, "adult", "Risk Categories", "reduced or no access to reliable transportation and/or major property loss", "risk=transport_property_loss", "Basic Needs - Financial & Utilities", new[] { "TRANSPORT" }, "E2", new string[0], "E3 goal generated per need", "Medium", "", ""),
            new Rule(9, "child", "Risk Categories", "vehicle or major property loss", "risk=vehicle_property_loss", "Basic Needs - Financial & Utilities", new[] { "TRANSPORT" }, "E2", new string[0], "", "Medium", "", ""),
            new Rule(10, "child", "Risk Categories", "reduced or no access to reliable transportation", "risk=transport", "Basic Needs - Financial & Utilities", new[] { "TRANSPORT" }, "E2", new string[0], "", "Medium", "", ""),
            new Rule(11, "both", "Risk Categories", "underemployment / unemployed (self or household)", "risk=underemployment|unemployed", "Basic Needs - Financial & Utilities", new[] { "INCOME_EMPLOYMENT" }, "E2", new[] { "G-14", "G-81" }, "E1 only if despair/rage present", "Medium", "", ""),
            new Rule(12, "both", "Risk Categories", "prolonged separation from social network / isolation", "risk=isolation", "Situational & Interpersonal", new[] { "SOCIAL_CONNECTION" }, "E2", new[] { "G-83" }, "", "Medium", "", ""),
            new Rule(13, "both", "Risk Categories", "illness or physical harm (self or household)", "risk=illness_harm", "Medical & Co-occurring", new[] { "MEDICAL_CARE" }, "E2", new[] { "G-92" }, "", "Medium", "", ""),
            new Rule(14, "both", "Risk Categories", "life was threatened", "risk=life_threatened", "Trauma & Triggers", new[] { "TRAUMA_TX" }, "E1", new[] { "G-50", "G-53", "G-49" }, "Check DV: partner violent -> goal 50 + DV_SAFETY", "High", "", ""),
            new Rule(15, "both", "Risk Categories", "witnessed death/injury", "risk=witnessed_death", "Trauma & Triggers", new[] { "TRAUMA_TX" }, "E1", new[] { "G-17", "G-53" }, "", "High", "", ""),
            new Rule(16, "both", "Risk Categories", "assisted with rescue/recovery", "risk=rescue_recovery", "Trauma & Triggers", new[] { "TRAUMA_TX" }, "E2", new[] { "G-58" }, "", "Medium", "", ""),
            new Rule(17, "both", "Risk Categories", "changed schools or learning format", "risk=changed_schools", "Child, Youth & Family", new[] { "SCHOOL_SUPPORT" }, "E2", new[] { "G-68" }, "", "Medium", "", ""),
            new Rule(18, "both", "Risk Categories", "evacuated quickly with no time to prepare", "risk=evacuated", "Basic Needs - Clothing & Hygiene", new[] { "HOUSING", "DISASTER_RECOVERY" }, "E1", new[] { "G-06", "G-87" }, "", "High", "", ""),
            new Rule(19, "both", "Risk Categories", "displaced from home", "risk=displaced", "Basic Needs - Shelter & Housing", new[] { "HOUSING" }, "E1", new[] { "G-08", "G-10", "G-12" }, "", "High", "", ""),
            new Rule(20, "both", "Risk Categories", "eviction due to unpaid rent", "risk=eviction", "Basic Needs - Shelter & Housing", new[] { "HOUSING", "LEGAL" }, "E1", new[] { "G-09" }, "", "High", "", ""),
            new Rule(21, "both", "Risk Categories", "utility disconnection", "risk=utility_disconnection", "Basic Needs - Financial & Utilities", new[] { "UTILITIES" }, "E1", new[] { "G-13" }, "", "High", "", ""),
            new Rule(22, "both", "Risk Categories", "sheltered in place / sought shelter (disaster or domestic abuse)", "risk=sheltered_danger", "Trauma & Triggers", new[] { "DV_SAFETY", "HOUSING" }, "E1", new[] { "G-50", "G-87" }, "", "High", "", ""),
            new Rule(23, "both", "Risk Categories", "past substance use / mental health problems", "risk=past_mh_su", "Mental Health Decompensation", new[] { "PSYCH_PROVIDER" }, "E2", new[] { "G-46", "G-45" }, "Ask about current provider and medication status", "Medium", "", ""),
            new Rule(24, "both", "Risk Categories", "pre-existing physical disability", "risk=physical_disability", "I/DD, Autism & Cognitive", new[] { "DISABILITY_RESOURCES" }, "E2", new string[0], "", "Medium", "", ""),
            new Rule(25, "both", "Risk Categories", "past trauma (list)", "risk=past_trauma", "Trauma & Triggers", new[] { "TRAUMA_TX" }, "E2", new[] { "G-49", "G-52" }, "", "Medium", "", ""),
            new Rule(26, "child", "Risk Categories", "natural disaster", "risk=natural_disaster", "Situational & Interpersonal", new[] { "DISASTER_RECOVERY" }, "E1", new[] { "G-87" }, "", "High", "", ""),
            new Rule(27, "both", "Risk Categories", "food insecurity", "risk=food_insecurity", "Basic Needs - Food", new[] { "FOOD" }, "E1", new[] { "G-01", "G-02", "G-03", "G-04" }, "Goal 2 when children present; 3 for older adult; 4 if diabetic/psychotropics", "High", "", ""),
            new Rule(28, "both", "Risk Categories", "reduced or no access to reliable information/communication", "risk=info_communication", "Situational & Interpersonal", new[] { "INFO_COMMUNICATION" }, "E2", new string[0], "", "Medium", "", ""),
            new Rule(29, "both", "Primary Risk", "Mental health", "primary=MentalHealth", "Mental Health Decompensation", new[] { "PSYCH_PROVIDER" }, "E2", new[] { "G-41", "G-43", "G-33" }, "Refine by diagnoses listed", "Medium", "", ""),
            new Rule(30, "both", "Primary Risk", "Substance abuse", "primary=SubstanceAbuse", "Substance Use", new[] { "SUD_TREATMENT" }, "E1", new[] { "G-59", "G-62", "G-63", "G-66" }, "", "High", "", ""),
            new Rule(31, "both", "Primary Risk", "Substance type = alcohol or benzodiazepine, daily use", "subst=alc_benzo_daily", "Substance Use", new[] { "WITHDRAWAL_MGMT", "MEDICAL_CARE" }, "HARD_STOP", new[] { "G-60" }, "Withdrawal can be fatal; medical clearance", "Urgent", "WITHDRAWAL RISK", "Daily alcohol or benzodiazepine use: withdrawal can be fatal. Medical clearance before any plan; do not advise abrupt stopping."),
            new Rule(32, "both", "Primary Risk", "Substance type = opioid", "subst=opioid", "Substance Use", new[] { "SUD_TREATMENT" }, "E1", new[] { "G-61", "G-65" }, "Naloxone in the home; goal 65 if pregnant", "High", "", ""),
            new Rule(33, "adult", "Demographics", "older adult (65+)", "age=Older65", "Situational & Interpersonal", new string[0], "E2", new[] { "G-03", "G-30", "G-83" }, "Older-adult variants preferred when suggesting", "Low", "", ""),
            new Rule(34, "child", "Demographics", "preschool (0-5)", "age=Preschool0_5", "Child, Youth & Family", new[] { "FAMILY_SUPPORT" }, "E2", new[] { "G-67" }, "Parent questions 16-20 become required", "Low", "", ""),
            new Rule(35, "both", "Demographics", "disability: physical", "dis=Physical", "I/DD, Autism & Cognitive", new[] { "DISABILITY_RESOURCES" }, "E2", new string[0], "", "Low", "", ""),
            new Rule(36, "both", "Demographics", "disability: intellectual/cognitive", "dis=Cognitive", "I/DD, Autism & Cognitive", new[] { "DISABILITY_RESOURCES" }, "E2", new[] { "G-75", "G-76", "G-79" }, "", "Low", "", ""),
            new Rule(37, "both", "Demographics", "disability: mental health/substance use", "dis=MHSU", "Mental Health Decompensation", new[] { "PSYCH_PROVIDER" }, "E2", new[] { "G-46" }, "", "Low", "", ""),
            new Rule(38, "both", "Demographics", "primary language Spanish / Other", "lang!=English", "Situational & Interpersonal", new[] { "LANGUAGE_ACCESS" }, "E2", new string[0], "Interpreter on every E3/E4 appointment", "Low", "", ""),
            new Rule(39, "both", "Demographics", "immigrated in past 5 years", "imm=Yes", "Situational & Interpersonal", new[] { "IMMIGRATION" }, "E2", new[] { "G-85" }, "", "Low", "", ""),
            new Rule(40, "adult", "Assessment Q1-11", "Q1 unwanted memories, nightmares, reminders", "q1>=4", "Trauma & Triggers", new[] { "TRAUMA_TX" }, "E2", new[] { "G-49" }, "", "Medium", "", ""),
            new Rule(41, "adult", "Assessment Q1-11", "Q2 lost enjoyment, distance from people, numb", "q2>=4", "Mental Health Decompensation", new[] { "PSYCH_PROVIDER", "SOCIAL_CONNECTION" }, "E2", new[] { "G-41" }, "", "Medium", "", ""),
            new Rule(42, "adult", "Assessment Q1-11", "Q3 avoidance of thinking/talking/reminders", "q3>=4", "Trauma & Triggers", new[] { "TRAUMA_TX" }, "E2", new[] { "G-49" }, "", "Medium", "", ""),
            new Rule(43, "adult", "Assessment Q1-11", "Q4 poor sleep, concentration, jumpiness, irritability", "q4>=4", "Trauma & Triggers", new[] { "TRAUMA_TX" }, "E2", new[] { "G-49", "G-42" }, "", "Medium", "", ""),
            new Rule(44, "adult", "Assessment Q1-11", "Q5 down or depressed", "q5>=4", "Mental Health Decompensation", new[] { "PSYCH_PROVIDER" }, "E2", new[] { "G-41" }, "", "Medium", "", ""),
            new Rule(45, "adult", "Assessment Q1-11", "Q6 ability to handle other stress harmed", "q6>=4", "Crisis Planning & Follow-up", new[] { "CRISIS_PLAN" }, "E2", new[] { "G-96" }, "", "Medium", "", ""),
            new Rule(46, "adult", "Assessment Q1-11", "Q7 physical health: eating, rest, smoking, alcohol/substances up", "q7>=4", "Substance Use", new[] { "SUD_TREATMENT", "MEDICAL_CARE" }, "E2", new[] { "G-62", "G-04" }, "", "Medium", "", ""),
            new Rule(47, "adult", "Assessment Q1-11", "Q8 distressed by own reactions", "q8>=4", "Mental Health Decompensation", new[] { "PSYCH_PROVIDER" }, "E2", new[] { "G-41" }, "", "Medium", "", ""),
            new Rule(48, "adult", "Assessment Q1-11", "Q9 interferes with work / daily activities", "q9>=4", "Situational & Interpersonal", new[] { "INCOME_EMPLOYMENT" }, "E2", new[] { "G-44", "G-81" }, "", "Medium", "", ""),
            new Rule(49, "adult", "Assessment Q1-11", "Q10 relationships / social activities affected", "q10>=4", "Situational & Interpersonal", new[] { "SOCIAL_CONNECTION", "FAMILY_SUPPORT" }, "E2", new[] { "G-74", "G-83" }, "", "Medium", "", ""),
            new Rule(50, "adult", "Assessment Q1-11", "Q11 concern about coping without further assistance", "q11>=4", "Crisis Planning & Follow-up", new[] { "CRISIS_PLAN", "FOLLOW_UP" }, "E2", new[] { "G-96", "G-97" }, "", "Medium", "", ""),
            new Rule(51, "adult", "Assessment Q1-11", "Score = count of 4/5 answers", "score>=4", "Mental Health Decompensation", new[] { "PSYCH_PROVIDER" }, "E2", new[] { "G-46" }, "Threshold mirrors child form (4+). Confirm with Eulanda.", "Medium", "", ""),
            new Rule(52, "adult", "Columbia", "C1 wished dead / not wake up", "s1=Yes", "Suicidality & Self-Harm", new[] { "SAFETY_SUICIDE" }, "E1", new[] { "G-24" }, "Passive SI: 72-hour supported plan", "High", "", ""),
            new Rule(53, "adult", "Columbia", "C2 thoughts of killing self", "s2=Yes", "Suicidality & Self-Harm", new[] { "SAFETY_SUICIDE", "PSYCH_PROVIDER" }, "E1", new[] { "G-24", "G-23" }, "Seek behavioral health evaluation; ask C3-C6", "High", "", ""),
            new Rule(54, "adult", "Columbia", "C3 thinking about method", "s3=Yes", "Suicidality & Self-Harm", new[] { "SAFETY_SUICIDE", "PSYCH_PROVIDER" }, "E1", new[] { "G-23", "G-89" }, "Ask about firearms in the home", "High", "", ""),
            new Rule(55, "adult", "Columbia", "C4 intention to act", "s4=Yes", "Suicidality & Self-Harm", new[] { "SAFETY_SUICIDE" }, "HARD_STOP", new[] { "G-23", "G-89" }, "HIGH RISK: 911 / ED / IVC protocol; stay with client", "Urgent", "HIGH RISK FOR SUICIDE", "Yes to Columbia 4, 5 or 6: get immediate help. Call 911 or go to the emergency room (IVC protocol). Stay with the client until evaluated."),
            new Rule(56, "adult", "Columbia", "C5 worked out details", "s5=Yes", "Suicidality & Self-Harm", new[] { "SAFETY_SUICIDE" }, "HARD_STOP", new[] { "G-23", "G-89" }, "HIGH RISK", "Urgent", "HIGH RISK FOR SUICIDE", "Yes to Columbia 4, 5 or 6: get immediate help. Call 911 or go to the emergency room (IVC protocol). Stay with the client until evaluated."),
            new Rule(57, "adult", "Columbia", "C6 prepared / started to act", "s6=Yes", "Suicidality & Self-Harm", new[] { "SAFETY_SUICIDE" }, "HARD_STOP", new[] { "G-23", "G-25", "G-89" }, "HIGH RISK; goal 25 if within 3 months", "Urgent", "HIGH RISK FOR SUICIDE", "Yes to Columbia 4, 5 or 6: get immediate help. Call 911 or go to the emergency room (IVC protocol). Stay with the client until evaluated."),
            new Rule(58, "adult", "Columbia", "C6 within past 3 months", "s6b=Yes", "Suicidality & Self-Harm", new[] { "SAFETY_SUICIDE" }, "HARD_STOP", new[] { "G-25" }, "Post-attempt follow-up enrollment", "Urgent", "RECENT SUICIDE ATTEMPT", "Attempt or preparation within the past 3 months: post-attempt follow-up enrollment, means restriction, and higher level of care evaluation."),
            new Rule(59, "child", "Assessment Q1-20", "Q1 upset/afraid/sad at reminders", "q1>=3", "Trauma & Triggers", new[] { "TRAUMA_TX" }, "E2", new[] { "G-53" }, "", "Medium", "", ""),
            new Rule(60, "child", "Assessment Q1-20", "Q2 bad dreams / nightmares", "q2>=3", "Trauma & Triggers", new[] { "TRAUMA_TX" }, "E2", new[] { "G-53" }, "", "Medium", "", ""),
            new Rule(61, "child", "Assessment Q1-20", "Q3 upsetting thoughts or pictures", "q3>=3", "Trauma & Triggers", new[] { "TRAUMA_TX" }, "E2", new[] { "G-53" }, "", "Medium", "", ""),
            new Rule(62, "child", "Assessment Q1-20", "Q4 tries not to think or talk about it", "q4>=3", "Trauma & Triggers", new[] { "TRAUMA_TX" }, "E2", new[] { "G-53" }, "", "Medium", "", ""),
            new Rule(63, "child", "Assessment Q1-20", "Q5 avoids places, people, things", "q5>=3", "Trauma & Triggers", new[] { "TRAUMA_TX" }, "E2", new[] { "G-53" }, "", "Medium", "", ""),
            new Rule(64, "child", "Assessment Q1-20", "Q6 difficulty sleeping", "q6>=3", "Trauma & Triggers", new[] { "TRAUMA_TX", "MEDICAL_CARE" }, "E2", new[] { "G-53" }, "", "Medium", "", ""),
            new Rule(65, "child", "Assessment Q1-20", "Q7 jumpy or nervous", "q7>=3", "Trauma & Triggers", new[] { "TRAUMA_TX" }, "E2", new[] { "G-53" }, "", "Medium", "", ""),
            new Rule(66, "child", "Assessment Q1-20", "Q8 harder to concentrate", "q8>=3", "Child, Youth & Family", new[] { "SCHOOL_SUPPORT" }, "E2", new[] { "G-68" }, "", "Medium", "", ""),
            new Rule(67, "child", "Assessment Q1-20", "Q9 irritable or grouchy", "q9>=3", "Child, Youth & Family", new[] { "FAMILY_SUPPORT" }, "E2", new[] { "G-67" }, "", "Medium", "", ""),
            new Rule(68, "child", "Assessment Q1-20", "Q10 sad, down, depressed", "q10>=3", "Mental Health Decompensation", new[] { "PSYCH_PROVIDER" }, "E2", new[] { "G-27" }, "", "Medium", "", ""),
            new Rule(69, "child", "Assessment Q1-20", "Q11 aches and pains", "q11>=3", "Medical & Co-occurring", new[] { "MEDICAL_CARE" }, "E2", new[] { "G-92" }, "", "Medium", "", ""),
            new Rule(70, "child", "Assessment Q1-20", "Q12 harder to get schoolwork done", "q12>=3", "Child, Youth & Family", new[] { "SCHOOL_SUPPORT" }, "E2", new[] { "G-68" }, "", "Medium", "", ""),
            new Rule(71, "child", "Assessment Q1-20", "Q13 worry something bad will happen", "q13>=3", "Child, Youth & Family", new[] { "PSYCH_PROVIDER" }, "E2", new[] { "G-68", "G-53" }, "", "Medium", "", ""),
            new Rule(72, "child", "Assessment Q1-20", "Q14 harder time with family or friends", "q14>=3", "Child, Youth & Family", new[] { "FAMILY_SUPPORT" }, "E2", new[] { "G-74", "G-67" }, "", "Medium", "", ""),
            new Rule(73, "child", "Assessment Q1-20", "Q15 harder to enjoy activities", "q15>=3", "Mental Health Decompensation", new[] { "PSYCH_PROVIDER" }, "E2", new[] { "G-27" }, "", "Medium", "", ""),
            new Rule(74, "child", "Assessment Q1-20", "Q16 parent: more clingy / separation worry", "q16>=3", "Child, Youth & Family", new[] { "FAMILY_SUPPORT" }, "E2", new[] { "G-67" }, "", "Medium", "", ""),
            new Rule(75, "child", "Assessment Q1-20", "Q17 parent: quieter, withdrawn", "q17>=3", "Child, Youth & Family", new[] { "PSYCH_PROVIDER", "FAMILY_SUPPORT" }, "E2", new[] { "G-27" }, "", "Medium", "", ""),
            new Rule(76, "child", "Assessment Q1-20", "Q18 parent: talks repeatedly about the disaster", "q18>=3", "Trauma & Triggers", new[] { "TRAUMA_TX" }, "E2", new[] { "G-53" }, "", "Medium", "", ""),
            new Rule(77, "child", "Assessment Q1-20", "Q19 parent: play is about the disaster", "q19>=3", "Trauma & Triggers", new[] { "TRAUMA_TX" }, "E2", new[] { "G-53" }, "", "Medium", "", ""),
            new Rule(78, "child", "Assessment Q1-20", "Q20 parent: behavior/development changes (bed-wetting, fighting, risk-taking, school decline)", "q20>=3", "Child, Youth & Family", new[] { "FAMILY_SUPPORT", "SCHOOL_SUPPORT" }, "E2", new[] { "G-67", "G-73" }, "", "Medium", "", ""),
            new Rule(79, "child", "Assessment Q1-20", "Total count of 3/4 answers", "score>=4", "Mental Health Decompensation", new[] { "PSYCH_PROVIDER" }, "E2", new string[0], "Form rule: discuss referral for services", "Medium", "", ""),
            new Rule(80, "child", "ASQ", "Q21 wished dead", "s1=Yes", "Suicidality & Self-Harm", new[] { "SAFETY_SUICIDE" }, "E1", new[] { "G-27", "G-24" }, "Positive screen: brief suicide safety assessment", "High", "", ""),
            new Rule(81, "child", "ASQ", "Q22 family better off if dead", "s2=Yes", "Suicidality & Self-Harm", new[] { "SAFETY_SUICIDE" }, "E1", new[] { "G-27", "G-24" }, "", "High", "", ""),
            new Rule(82, "child", "ASQ", "Q23 thoughts of killing self (past week)", "s3=Yes", "Suicidality & Self-Harm", new[] { "SAFETY_SUICIDE", "PSYCH_PROVIDER" }, "E1", new[] { "G-27", "G-23", "G-89" }, "Ask about firearms/means", "High", "", ""),
            new Rule(83, "child", "ASQ", "Q24 ever tried to kill self", "s4=Yes", "Suicidality & Self-Harm", new[] { "SAFETY_SUICIDE" }, "E1", new[] { "G-27", "G-25" }, "", "High", "", ""),
            new Rule(84, "child", "ASQ", "Q25 thoughts right now (acuity)", "s5=Yes", "Suicidality & Self-Harm", new[] { "SAFETY_SUICIDE" }, "HARD_STOP", new[] { "G-23", "G-27", "G-89" }, "ACUTE: immediate psychiatric intervention; do not leave alone", "Urgent", "ACUTE SUICIDE RISK", "Child answered yes to the acuity question: immediate psychiatric intervention. Do not leave the child alone."),
            new Rule(85, "both", "Referral", "crisis counseling program services", "ref=crisis_counseling", "Crisis Planning & Follow-up", new[] { "FOLLOW_UP" }, "E2", new[] { "G-97" }, "", "Medium", "", ""),
            new Rule(86, "both", "Referral", "mental health services", "ref=mental_health", "Mental Health Decompensation", new[] { "PSYCH_PROVIDER" }, "E2", new string[0], "", "Medium", "", ""),
            new Rule(87, "both", "Referral", "substance use services", "ref=substance_use", "Substance Use", new[] { "SUD_TREATMENT" }, "E2", new string[0], "", "Medium", "", ""),
            new Rule(88, "both", "Referral", "community services (FEMA, loans, housing, employment, social services)", "ref=community", "Basic Needs - Financial & Utilities", new[] { "HOUSING", "INCOME_EMPLOYMENT", "DISASTER_RECOVERY" }, "E2", new string[0], "Clinician picks which sub-needs", "Medium", "", ""),
            new Rule(89, "both", "Referral", "resources for disabilities / access needs", "ref=disability", "I/DD, Autism & Cognitive", new[] { "DISABILITY_RESOURCES" }, "E2", new string[0], "", "Medium", "", ""),
            new Rule(90, "adult", "Referral", "participant accepted referral(s)", "refaccept=No", "Trauma & Triggers", new[] { "ENGAGEMENT" }, "E1", new[] { "G-57" }, "Trust-building goal; retry at E2", "High", "", ""),
            new Rule(91, "child", "Referral", "referral accepted by child / by parent", "refaccept_cp=No", "Child, Youth & Family", new[] { "ENGAGEMENT", "FAMILY_SUPPORT" }, "E1", new[] { "G-57", "G-70" }, "", "High", "", ""),
            new Rule(92, "both", "Always", "Every episode", "always", "Crisis Planning & Follow-up", new[] { "CRISIS_PLAN", "FOLLOW_UP" }, "E5", new[] { "G-96", "G-97", "G-100" }, "Crisis Plan before discharge (NC 8A); day 7/14/21 contacts", "Low", "", ""),
            new Rule(93, "both", "Always", "Second episode within 90 days", "repeat90", "Crisis Planning & Follow-up", new[] { "FOLLOW_UP" }, "E1", new[] { "G-99" }, "Prevention plan", "High", "", ""),
        };

        static readonly Regex AlcBenzo = new Regex("alcohol|beer|liquor|wine|vodka|benzo|xanax|alprazolam|klonopin|clonazepam|valium|diazepam|ativan|lorazepam", RegexOptions.IgnoreCase);
        static readonly Regex Opioid = new Regex("opioid|opiate|heroin|fentanyl|oxy|percocet|hydrocodone|vicodin|methadone|suboxone|morphine|codeine|tramadol", RegexOptions.IgnoreCase);

        static bool Has(string list, string key) => !string.IsNullOrEmpty(list) && list.Split('|').Contains(key);
        static bool HasAny(string list, string keys) => keys.Split('|').Any(k => Has(list, k));

        public static int? Q(CrisisAssessmentsRow a, int n) => n switch
        {
            1 => a.Q1,
            2 => a.Q2,
            3 => a.Q3,
            4 => a.Q4,
            5 => a.Q5,
            6 => a.Q6,
            7 => a.Q7,
            8 => a.Q8,
            9 => a.Q9,
            10 => a.Q10,
            11 => a.Q11,
            12 => a.Q12,
            13 => a.Q13,
            14 => a.Q14,
            15 => a.Q15,
            16 => a.Q16,
            17 => a.Q17,
            18 => a.Q18,
            19 => a.Q19,
            20 => a.Q20,
            _ => null
        };
        public static string S(CrisisAssessmentsRow a, int n) => n switch
        {
            1 => a.S1,
            2 => a.S2,
            3 => a.S3,
            4 => a.S4,
            5 => a.S5,
            6 => a.S6,
            _ => null
        };

        public static bool IsChild(CrisisAssessmentsRow a) => string.Equals(a.FormType, "Child", StringComparison.OrdinalIgnoreCase);

        public static int Score(CrisisAssessmentsRow a)
        {
            bool child = IsChild(a);
            int n = child ? ChildQuestions : AdultQuestions, t = child ? ChildTrigger : AdultTrigger, score = 0;
            for (int i = 1; i <= n; i++) if ((Q(a, i) ?? -1) >= t) score++;
            return score;
        }

        public static bool Eval(Rule r, CrisisAssessmentsRow a, int score, bool repeat90)
        {
            var form = IsChild(a) ? "child" : "adult";
            if (r.Form != "both" && r.Form != form) return false;
            var p = r.Predicate;
            string v(string prefix) => p.Substring(prefix.Length);
            if (p == "always") return true;
            if (p == "repeat90") return repeat90;
            if (p == "childhome") return a.ChildrenInHome == true;
            if (p.StartsWith("loc=")) return a.Location == v("loc=");
            if (p.StartsWith("risk=")) return HasAny(a.RiskCategories, v("risk="));
            if (p.StartsWith("primary=")) return a.PrimaryRisk == v("primary=");
            if (p == "subst=alc_benzo_daily") return !string.IsNullOrEmpty(a.SubstanceType) && AlcBenzo.IsMatch(a.SubstanceType) && a.SubstanceFrequency == "Daily";
            if (p == "subst=opioid") return !string.IsNullOrEmpty(a.SubstanceType) && Opioid.IsMatch(a.SubstanceType);
            if (p.StartsWith("age=")) return a.AgeBand == v("age=");
            if (p.StartsWith("dis=")) return Has(a.Disabilities, v("dis="));
            if (p == "lang!=English") return !string.IsNullOrEmpty(a.Language) && a.Language != "English";
            if (p == "imm=Yes") return a.Immigrated == "Yes";
            if (p.StartsWith("score>=")) return score >= int.Parse(v("score>="));
            if (p.StartsWith("q"))
            {
                var parts = p.Substring(1).Split(new[] { ">=" }, StringSplitOptions.None);
                return (Q(a, int.Parse(parts[0])) ?? -1) >= int.Parse(parts[1]);
            }
            if (p == "s6b=Yes") return a.S6b == "Yes";
            if (p.StartsWith("s") && p.EndsWith("=Yes")) return S(a, int.Parse(p.Substring(1, p.IndexOf('=') - 1))) == "Yes";
            if (p.StartsWith("ref=")) return Has(a.Referrals, v("ref="));
            if (p == "refaccept=No") return a.ReferralAccepted == "No";
            if (p == "refaccept_cp=No") return a.ReferralAcceptedChild == "No" || a.ReferralAcceptedParent == "No";
            return false;
        }
    }
}
