-- Plain SQL mirror of migration 20260914_0100 (for Malik / manual deploys)
IF OBJECT_ID('dbo.CrisisAssessments') IS NULL
BEGIN
CREATE TABLE [dbo].[CrisisAssessments] (
    [AssessmentId] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    [TenantId] INT NULL,
    [ClientId] INT NOT NULL,
    [EpisodeId] INT NULL,
    [FormType] NVARCHAR(10) NOT NULL DEFAULT 'Adult',
    [Status] NVARCHAR(20) NOT NULL DEFAULT 'Draft',
    [ServiceDate] DATETIME NULL,
    [StartTime] NVARCHAR(10) NULL,
    [EndTime] NVARCHAR(10) NULL,
    [County] NVARCHAR(100) NULL,
    [Zip] NVARCHAR(10) NULL,
    [TeamMember1] INT NULL,
    [TeamMember2] INT NULL,
    [ResponderCredentials] NVARCHAR(200) NULL,
    [ParentPresent] NVARCHAR(3) NULL,
    [ParentName] NVARCHAR(200) NULL,
    [ParentPhone] NVARCHAR(40) NULL,
    [GradeLevel] NVARCHAR(20) NULL,
    [Location] NVARCHAR(40) NULL,
    [ChildrenInHome] BIT NULL,
    [RiskCategories] NVARCHAR(2000) NULL,
    [PrimaryRisk] NVARCHAR(20) NULL,
    [Diagnoses] NVARCHAR(1000) NULL,
    [SubstanceType] NVARCHAR(100) NULL,
    [SubstanceAmount] NVARCHAR(100) NULL,
    [SubstanceFrequency] NVARCHAR(20) NULL,
    [AgeBand] NVARCHAR(20) NULL,
    [Disabilities] NVARCHAR(100) NULL,
    [Gender] NVARCHAR(20) NULL,
    [Language] NVARCHAR(20) NULL,
    [RaceEthnicity] NVARCHAR(200) NULL,
    [Immigrated] NVARCHAR(3) NULL,
    [Q1] INT NULL,
    [Q2] INT NULL,
    [Q3] INT NULL,
    [Q4] INT NULL,
    [Q5] INT NULL,
    [Q6] INT NULL,
    [Q7] INT NULL,
    [Q8] INT NULL,
    [Q9] INT NULL,
    [Q10] INT NULL,
    [Q11] INT NULL,
    [Q12] INT NULL,
    [Q13] INT NULL,
    [Q14] INT NULL,
    [Q15] INT NULL,
    [Q16] INT NULL,
    [Q17] INT NULL,
    [Q18] INT NULL,
    [Q19] INT NULL,
    [Q20] INT NULL,
    [S1] NVARCHAR(3) NULL,
    [S2] NVARCHAR(3) NULL,
    [S3] NVARCHAR(3) NULL,
    [S4] NVARCHAR(3) NULL,
    [S5] NVARCHAR(3) NULL,
    [S6] NVARCHAR(3) NULL,
    [S6b] NVARCHAR(3) NULL,
    [Score] INT NULL,
    [HighRisk] BIT NOT NULL DEFAULT 0,
    [HardStopReasons] NVARCHAR(1000) NULL,
    [Referrals] NVARCHAR(200) NULL,
    [ReferralAccepted] NVARCHAR(3) NULL,
    [ReferralAcceptedChild] NVARCHAR(3) NULL,
    [ReferralAcceptedParent] NVARCHAR(3) NULL,
    [ProjectedDischarge] DATETIME NULL,
    [Narrative] NVARCHAR(4000) NULL,
    [CompletedAt] DATETIME NULL,
    [SignedBy] INT NULL,
    [SignedAt] DATETIME NULL,
    [SignedName] NVARCHAR(200) NULL,
    [Owner] INT NULL,
    [OwnerCreateDate] DATETIME NULL
);
CREATE INDEX IX_CrisisAssessments_Client ON dbo.CrisisAssessments(ClientId);
END
IF OBJECT_ID('dbo.CrisisAssessmentNeeds') IS NULL
BEGIN
CREATE TABLE [dbo].[CrisisAssessmentNeeds] (
    [NeedRecId] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    [AssessmentId] INT NOT NULL,
    [EpisodeId] INT NULL,
    [ClientId] INT NOT NULL,
    [TenantId] INT NULL,
    [NeedKey] NVARCHAR(40) NOT NULL,
    [Priority] NVARCHAR(10) NULL,
    [Source] NVARCHAR(1000) NULL,
    [Accepted] BIT NOT NULL DEFAULT 1,
    [Status] NVARCHAR(30) NOT NULL DEFAULT 'Identified',
    [SortOrder] INT NULL,
    [GoalsCreated] INT NULL
);
CREATE INDEX IX_CrisisAssessmentNeeds_Assessment ON dbo.CrisisAssessmentNeeds(AssessmentId);
END
