CREATE TABLE [dbo].[Clients] (
    [ClientId]                       INT             IDENTITY (53, 1) NOT NULL,
    [FirstName]                      NVARCHAR (50)   CONSTRAINT [DF__clients__firstNa__5535A963] DEFAULT (NULL) NULL,
    [MiddleName]                     NVARCHAR (50)   CONSTRAINT [DF__clients__middleN__5629CD9C] DEFAULT (NULL) NULL,
    [LastName]                       NVARCHAR (50)   CONSTRAINT [DF__clients__lastNam__571DF1D5] DEFAULT (NULL) NULL,
    [MaidenName]                     NVARCHAR (50)   NULL,
    [OtherName]                      NVARCHAR (100)  NULL,
    [BirthDate]                      DATE            CONSTRAINT [DF__clients__dob__5812160E] DEFAULT (NULL) NULL,
    [Race]                           NVARCHAR (50)   CONSTRAINT [DF__clients__race__59063A47] DEFAULT (NULL) NULL,
    [Gender]                         NVARCHAR (10)   CONSTRAINT [DF__clients__gender__59FA5E80] DEFAULT (NULL) NULL,
    [Ethnicity]                      NVARCHAR (50)   NULL,
    [MaritalStatus]                  NVARCHAR (25)   NULL,
    [SocialSecurityNum]              NVARCHAR (15)   NULL,
    [Address1]                       NVARCHAR (50)   CONSTRAINT [DF__clients__address__5AEE82B9] DEFAULT (NULL) NULL,
    [Address2]                       NVARCHAR (50)   CONSTRAINT [DF__clients__address__5BE2A6F2] DEFAULT (NULL) NULL,
    [City]                           NVARCHAR (50)   CONSTRAINT [DF__clients__city__5CD6CB2B] DEFAULT (NULL) NULL,
    [State]                          NVARCHAR (2)    CONSTRAINT [DF__clients__state__5DCAEF64] DEFAULT (NULL) NULL,
    [Zipcode]                        NVARCHAR (10)   CONSTRAINT [DF_Clients_State1] DEFAULT (NULL) NULL,
    [County]                         NVARCHAR (100)  CONSTRAINT [DF__clients__county__68487DD7] DEFAULT (NULL) NULL,
    [PrimaryPhone]                   NVARCHAR (15)   CONSTRAINT [DF__clients__primary__5EBF139D] DEFAULT (NULL) NULL,
    [SecondaryPhone]                 NVARCHAR (15)   CONSTRAINT [DF__clients__seconda__5FB337D6] DEFAULT (NULL) NULL,
    [CellPhone]                      NVARCHAR (15)   NULL,
    [Email]                          NVARCHAR (100)  NULL,
    [CountryOfBirth]                 VARCHAR (50)    NULL,
    [IsVeteran]                      INT             NULL,
    [PrimaryLanguage]                NVARCHAR (50)   NULL,
    [NextOfKinName]                  NVARCHAR (100)  NULL,
    [NextOfKinPhone]                 NVARCHAR (15)   NULL,
    [MothersName]                    NVARCHAR (100)  NULL,
    [FathersName]                    NVARCHAR (100)  NULL,
    [LicenseStateId]                 NVARCHAR (50)   NULL,
    [EmploymentStatus]               NVARCHAR (25)   NULL,
    [NumberInHouse]                  INT             NULL,
    [LivingArrangements]             NVARCHAR (25)   NULL,
    [GrossIncomeDollar]              DECIMAL (18, 2) NULL,
    [GrossIncomePer]                 NVARCHAR (50)   NULL,
    [NumberDepenentIncome]           NVARCHAR (50)   NULL,
    [EducationLevel]                 NVARCHAR (50)   NULL,
    [NameOfSchool]                   NVARCHAR (100)  NULL,
    [PrimaryInsuranceTypeId]         INT             NULL,
    [PrimaryInsuranceNumber]         NVARCHAR (100)  NULL,
    [PrimaryInsuranceGroup]          NVARCHAR (100)  NULL,
    [PrimaryInsuranceHolder]         NVARCHAR (100)  NULL,
    [PrimaryInsuranceHolderDob]      DATE            NULL,
    [PrimaryInsuranceRelationship]   NVARCHAR (100)  NULL,
    [PrimaryInsuranceAddress1]       NVARCHAR (100)  NULL,
    [PrimaryInsuranceCity]           NVARCHAR (100)  NULL,
    [PrimaryInsuranceState]          NVARCHAR (100)  NULL,
    [PrimaryInsuranceZipCode]        NVARCHAR (50)   NULL,
    [SecondaryInsuranceTypeId]       INT             NULL,
    [SecondaryInsuranceNumber]       NVARCHAR (100)  NULL,
    [SecondaryInsuranceGroup]        NVARCHAR (100)  NULL,
    [SecondaryInsuranceHolder]       NVARCHAR (100)  NULL,
    [SecondaryInsuranceHolderDob]    DATE            NULL,
    [SecondaryInsuranceRelationship] NVARCHAR (100)  NULL,
    [SecondaryInsuranceAddress1]     NVARCHAR (100)  NULL,
    [SecondaryInsuranceCity]         NVARCHAR (100)  NULL,
    [SecondaryInsuranceState]        NVARCHAR (100)  NULL,
    [SecondaryInsuranceZipCode]      NVARCHAR (50)   NULL,
    [DischargeDate]                  DATE            CONSTRAINT [DF__clients__dischar__6383C8BA] DEFAULT (NULL) NULL,
    [DiagnosisDate]                  DATE            CONSTRAINT [DF__clients__diagnos__60A75C0F] DEFAULT (NULL) NULL,
    [PlanExpirationDate]             DATE            CONSTRAINT [DF__clients__planExp__619B8048] DEFAULT (NULL) NULL,
    [AdmissionDate]                  DATE            CONSTRAINT [DF__clients__admissi__628FA481] DEFAULT (NULL) NULL,
    [ReferralDate]                   DATE            CONSTRAINT [DF__clients__referra__656C112C] DEFAULT (NULL) NULL,
    [ReferralSource]                 NVARCHAR (25)   CONSTRAINT [DF__clients__referra__66603565] DEFAULT (NULL) NULL,
    [DiagnosisNotes]                 NVARCHAR (2000) CONSTRAINT [DF__clients__diagnos__6477ECF3] DEFAULT (NULL) NULL,
    [GuardianName]                   NVARCHAR (100)  CONSTRAINT [DF__clients__guardia__6754599E] DEFAULT (NULL) NULL,
    [Notes]                          NVARCHAR (500)  NULL,
    [SystemStatus]                   NVARCHAR (25)   CONSTRAINT [DF__clients__systemS__693CA210] DEFAULT (NULL) NULL,
    [ClientStatus]                   NVARCHAR (25)   NOT NULL,
    [SiteTypeId]                     INT             NULL,
    [TenantId]                       INT             NULL,
    [RecordNumber]                   NVARCHAR (100)  NOT NULL,
    [Pcn]                            NVARCHAR (50)   NULL,
    [OriginalServiceDate]            DATE            NULL,
    [EmergencyPerson]                NVARCHAR (100)  NULL,
    [EmergencyPhone]                 NVARCHAR (15)   NULL,
    [PreferredPhysician]             NVARCHAR (50)   NULL,
    [PreferredPhysicianAddress]      NVARCHAR (100)  NULL,
    [PreferredPhysicianCounty]       NVARCHAR (50)   NULL,
    [PreferredPhysicianPhone]        NVARCHAR (15)   NULL,
    [PharmacyUsed]                   NVARCHAR (100)  NULL,
    [PharmacyPhone]                  NVARCHAR (15)   NULL,
    [Allergies]                      NVARCHAR (50)   NULL,
    [AllergiesMoreInfo]              NVARCHAR (300)  NULL,
    CONSTRAINT [PK_clients_id] PRIMARY KEY CLUSTERED ([ClientId] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'geniusone2x.clients', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Clients';

