CREATE TABLE [dbo].[ConsentRequests] (
    [RequestId] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    [EpisodeId] INT NOT NULL,
    [ClientId] INT NOT NULL,
    [TemplateId] INT NOT NULL,
    [Status] NVARCHAR(20) NOT NULL DEFAULT 'Pending',
    [Channel] NVARCHAR(20) NULL,
    [SignedAt] DATETIME NULL,
    [SignerName] NVARCHAR(200) NULL,
    [SignerRelationship] NVARCHAR(60) NULL,
    [SignatureImage] NVARCHAR(MAX) NULL,
    [WorkerUserId] INT NULL,
    [WorkerName] NVARCHAR(200) NULL,
    [WorkerSignatureImage] NVARCHAR(MAX) NULL,
    [WorkerSignedAt] DATETIME NULL,
    [FieldData] NVARCHAR(MAX) NULL,
    [IpAddress] NVARCHAR(64) NULL,
    [UserAgent] NVARCHAR(400) NULL,
    [DocumentHash] NVARCHAR(64) NULL,
    [ClientDocumentId] INT NULL,
    [RefusalReason] NVARCHAR(500) NULL,
    [WrittenDueAt] DATETIME NULL,
    [CreatedAt] DATETIME NOT NULL,
    [CreatedBy] INT NULL,
    [TenantId] INT NULL
);
