CREATE TABLE [dbo].[Users] (
    [UserId]                  INT             IDENTITY (1, 1) NOT NULL,
    [Username]                NVARCHAR (100)  NOT NULL,
    [DisplayName]             NVARCHAR (100)  NOT NULL,
    [Email]                   NVARCHAR (100)  NULL,
    [Source]                  NVARCHAR (4)    NOT NULL,
    [PasswordHash]            NVARCHAR (86)   NOT NULL,
    [PasswordSalt]            NVARCHAR (10)   NOT NULL,
    [LastDirectoryUpdate]     DATETIME        NULL,
    [UserImage]               NVARCHAR (100)  NULL,
    [InsertDate]              DATETIME        NOT NULL,
    [InsertUserId]            INT             NOT NULL,
    [UpdateDate]              DATETIME        NULL,
    [UpdateUserId]            INT             NULL,
    [IsActive]                SMALLINT        CONSTRAINT [DF_Users_IsActive] DEFAULT ((1)) NOT NULL,
    [Type]                    NVARCHAR (50)   NULL,
    [Classification]          NVARCHAR (50)   NULL,
    [EmployeeId]              NVARCHAR (25)   NULL,
    [FirstName]               NVARCHAR (50)   NULL,
    [MiddleName]              NVARCHAR (50)   NULL,
    [LastName]                NVARCHAR (50)   NULL,
    [Address1]                NVARCHAR (50)   NULL,
    [Address2]                NVARCHAR (50)   NULL,
    [City]                    NVARCHAR (50)   NULL,
    [State]                   NVARCHAR (2)    NULL,
    [Zipcode]                 NVARCHAR (10)   NULL,
    [PrimaryPhone]            NVARCHAR (15)   NULL,
    [SecondaryPhone]          NVARCHAR (15)   NULL,
    [HireDate]                DATE            NULL,
    [EmergencyContact]        NVARCHAR (100)  NULL,
    [EmergencyContactPhone]   NVARCHAR (15)   NULL,
    [SocialSecurityNumber]    NVARCHAR (11)   NULL,
    [DriverLicenseNumber]     NVARCHAR (50)   NULL,
    [DriverLicenseState]      NVARCHAR (2)    NULL,
    [DriverLicenseExpiration] DATE            NULL,
    [Notes]                   NVARCHAR (255)  NULL,
    [eSignatureBase64]        NVARCHAR (MAX)  NULL,
    [eSignaturePlainText]     NVARCHAR (255)  NULL,
    [SignatureVerified]       BIT             CONSTRAINT [DF_Users_SignatureVerified] DEFAULT ((0)) NULL,
    [IsWorker]                BIT             NULL,
    [RecAlerts]               BIT             NULL,
    [TenantId]                INT             NULL,
    [BillRateAdmin]           DECIMAL (18, 2) NULL,
    [BillRateTraining]        DECIMAL (18, 2) NULL,
    [BillRateMeeting]         DECIMAL (18, 2) NULL,
    [BillRateClientOnTime]    DECIMAL (18, 2) NULL,
    [BillRateClientLate]      DECIMAL (18, 2) NULL,
    [MobilePhoneNumber]       NVARCHAR (20)   NULL,
    [MobilePhoneVerified]     BIT             CONSTRAINT [DF_Users_MobilePhoneVerified] DEFAULT ((0)) NOT NULL,
    [TwoFactorAuth]           INT             NULL,
    [Npi]                     NVARCHAR (50)   NULL,
    [Taxonomy]                NVARCHAR (50)   NULL,
    CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED ([UserId] ASC)
);

